default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: csv_transformer_development

test:
  <<: *default
  database: csv_transformer_test

production:
  <<: *default
  database: csv_transformer_production
